---
- name: Deploy Lab
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "vcsa.vclass.rapa"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "VMware123!"
    datacenter_name: "RAPA" 
    esxi_username: "root"
    esxi_password: "VMware123!"
    parent_folder: "3.Class/" 
    snapshot_name: "Setup"
    
    LAB_SID: 
    - { id: S00, host: esx-01.vclass.rapa, ds: vSAN-ESX-01, Temp_ESX: Temp-ESX-01 }

    LAB_PGs:
    - { name: SB-Mgmt,   vid: 20 }
    - { name: SB-vSAN,   vid: 23 }
    - { name: SB-vMotion,vid: 24 }
    - { name: SC-Mgmt,   vid: 30 }

    ESX_VMs:
    - { name: esx-04,    ip: 10.10.10.14,  gw: 10.10.10.1,  vlan: 10 }
    - { name: sb-esx-01, ip: 10.10.20.11,  gw: 10.10.20.1,  vlan: 20 }
    - { name: sb-esx-02, ip: 10.10.20.12,  gw: 10.10.20.1,  vlan: 20 }
    - { name: sb-esx-03, ip: 10.10.20.13,  gw: 10.10.20.1,  vlan: 20 }
    - { name: sb-esx-04, ip: 10.10.20.14,  gw: 10.10.20.1,  vlan: 20 }


  tasks:

  - name: 01.Adding LAB Portgroups to LAB Switch
    community.vmware.vmware_portgroup:
      hostname: "{{ item[0].host }}"
      username: "{{ esxi_username }}"
      password: "{{ esxi_password }}"
      esxi_hostname: "{{ item[0].host }}"
      validate_certs: no
      switch: "{{ item[0].id }}"
      portgroup: "{{ item[0].id }}-{{ item[1].name }}"
      vlan_id: "{{ item[1].vid }}"
    loop: "{{ LAB_SID | product(LAB_PGs) | list }}"
    delegate_to: localhost

  - name: 02.Deploy ESX VMs
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      folder: "{{ parent_folder }}{{ item[0].id }}"
      name: "{{ item[0].id }}-{{ item[1].name }}"
      state: poweredoff
      esxi_hostname: "{{ item[0].host }}"
      template: "{{ item[0].Temp_ESX }}"
      linked_clone: True
      snapshot_src: "{{ snapshot_name }}"      
    loop: "{{ LAB_SID | product(ESX_VMs) | list }}"
    delegate_to: localhost


  - name: 03.Change ESX VMs Nics
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      folder: "{{ parent_folder }}{{ item[0].id }}"
      name: "{{ item[0].id }}-{{ item[1].name }}"
      esxi_hostname: "{{ item[0].host }}"
      datastore: "{{ item[0].ds }}"
      networks:
        - name: "{{ item[0].id }}-Trunk"
          label: "Network adapter 1"
        - name: "{{ item[0].id }}-Trunk"
          label: "Network adapter 2"
        - name: "{{ item[0].id }}-Trunk"
          label: "Network adapter 3"
        - name: "{{ item[0].id }}-Trunk"
          label: "Network adapter 4"
    loop: "{{ LAB_SID | product(ESX_VMs) | list }}"
    delegate_to: localhost


  - name: 04.Power on ESXi VMs
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      folder: "{{ parent_folder }}{{ item[0].id }}"
      name: "{{ item[0].id }}-{{ item[1].name }}"
      state: "poweredon"
    loop: "{{ LAB_SID | product(ESX_VMs) | list }}"
    delegate_to: localhost

  - name: 05. Waiting 120 seconds for booting
    wait_for:
      timeout: 120
    delegate_to: localhost

  - name: 06. Configure ESX VMs and Shutdown (Final Bulletproof Version)
    community.vmware.vmware_vm_shell:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      vm_id: "{{ item[0].id }}-{{ item[1].name }}"
      vm_id_type: vm_name
      vm_username: 'root'
      vm_password: 'VMware123!'
      vm_shell: /bin/sh
      vm_shell_cwd: "/tmp"
      vm_shell_args: |
        -c "nohup sh -c '
        echo --- Start Configuration --- > /tmp/ansible_config.log 2>&1
        /bin/esxcli system settings advanced set -o /Net/FollowHardwareMac -i 1 >> /tmp/ansible_config.log 2>&1
        /bin/sed -i \"s#/system/uuid.*##\" /etc/vmware/esx.conf >> /tmp/ansible_config.log 2>&1
        /bin/esxcli network vswitch standard portgroup set -p \"Management Network\" -v {{ item[1].vlan }} >> /tmp/ansible_config.log 2>&1
        /bin/esxcli system hostname set --host {{ item[1].name }} >> /tmp/ansible_config.log 2>&1
        /bin/esxcli system hostname set --domain vclass.local >> /tmp/ansible_config.log 2>&1
        /bin/esxcli network ip dns server add -s 10.10.10.1 >> /tmp/ansible_config.log 2>&1
        /bin/esxcli network ip dns search add -d vclass.local >> /tmp/ansible_config.log 2>&1
        /bin/vim-cmd hostsvc/datastore/remove datastore1 >> /tmp/ansible_config.log 2>&1
        /bin/vim-cmd hostsvc/advopt/update UserVars.SuppressShellWarning long 1 >> /tmp/ansible_config.log 2>&1
        
        echo \"Applying IP Address: {{ item[1].ip }}\" >> /tmp/ansible_config.log 2>&1
        /bin/esxcli network ip interface ipv4 set -i vmk0 -t static -I {{ item[1].ip }} -N 255.255.255.0 -g {{ item[1].gw }} >> /tmp/ansible_config.log 2>&1
        
        echo \"Generating Certificates...\" >> /tmp/ansible_config.log 2>&1
        /sbin/generate-certificates >> /tmp/ansible_config.log 2>&1
        
        echo --- Config Finished --- >> /tmp/ansible_config.log 2>&1
        sleep 5
        ' > /dev/null 2>&1 &"
      wait_for_process: False
    loop: "{{ LAB_SID | product(ESX_VMs) | list }}"
    delegate_to: localhost
      # /sbin/poweroff
  

    
  # - name: 07. Reboot ESX VMs
  #   community.vmware.vmware_guest_powerstate:
  #     hostname: "{{ vcenter_hostname }}"
  #     username: "{{ vcenter_username }}"
  #     password: "{{ vcenter_password }}"
  #     validate_certs: no
  #     datacenter: "{{ datacenter_name }}"
  #     folder: "{{ parent_folder }}{{ item[0].id }}"
  #     name: "{{ item[0].id }}-{{ item[1].name }}"
  #     state: reboot-guest
  #   loop: "{{ LAB_SID | product(ESX_VMs) | list }}"
  #   delegate_to: localhost
