---
- name: Deploy vSphere Lab
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "vcsa.vclass.rapa"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "VMware123!"
    datacenter_name: "RAPA" 
    esxi_username: "root"
    esxi_password: "VMware123!"
    parent_folder: "3.Class/" 

    LAB_SID: 
    # - { id: S00, host: esx-01.vclass.rapa, ds: vSAN-ESX-01, Temp_DC: Temp-WinSvr-ESX-01 }
    # - { id: S01, host: esx-01.vclass.rapa, ds: vSAN-ESX-01, Temp_DC: Temp-WinSvr-ESX-01 }
    # - { id: S02, host: esx-01.vclass.rapa, ds: vSAN-ESX-01, Temp_DC: Temp-WinSvr-ESX-01 }
    # - { id: S03, host: esx-01.vclass.rapa, ds: vSAN-ESX-01, Temp_DC: Temp-WinSvr-ESX-01 }
    # - { id: S04, host: esx-01.vclass.rapa, ds: vSAN-ESX-01, Temp_DC: Temp-WinSvr-ESX-01 }
    # - { id: S05, host: esx-02.vclass.rapa, ds: vSAN-ESX-02, Temp_DC: Temp-WinSvr-ESX-02 }
    # - { id: S06, host: esx-02.vclass.rapa, ds: vSAN-ESX-02, Temp_DC: Temp-WinSvr-ESX-02 }
    # - { id: S07, host: esx-02.vclass.rapa, ds: vSAN-ESX-02, Temp_DC: Temp-WinSvr-ESX-02 }
    # - { id: S08, host: esx-02.vclass.rapa, ds: vSAN-ESX-02, Temp_DC: Temp-WinSvr-ESX-02 }
    # - { id: S09, host: esx-02.vclass.rapa, ds: vSAN-ESX-02, Temp_DC: Temp-WinSvr-ESX-02 }

    LAB_PGs:
    - { name: Trunk,   vid: 4095 }
    - { name: Mgmt,    vid:   10 }
    - { name: iSCSI-1, vid:   11 }
    - { name: iSCSI-2, vid:   12 }
    - { name: vMotion, vid:   14 }
    - { name: Prod,    vid:   15 }


    LAB_ESX_VMs:
    - { name: esx-01 }
    - { name: esx-02 }
    - { name: esx-03 }

  tasks:

  - name: 01. Adding LAB Portgroups to LAB Switch
    community.vmware.vmware_portgroup:
      hostname: "{{ item[0].host }}"
      username: "{{ esxi_username }}"
      password: "{{ esxi_password }}"
      esxi_hostname: "{{ item[0].host }}"
      validate_certs: no
      switch: "{{ item[0].id }}"
      portgroup: "{{ item[0].id }}-{{ item[1].name }}"
      vlan_id: "{{ item[1].vid }}"
    loop: "{{ LAB_SID | product(LAB_PGs) | list }}"
    delegate_to: localhost

  - name: 02. Create LAB ESX VMs
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{datacenter_name}}"
      folder: "{{ parent_folder }}{{ item[0].id }}"
      name: "{{ item[0].id }}-{{ item[1].name }}"
      state: poweredoff
      guest_id: vmkernel8Guest
      esxi_hostname: "{{ item[0].host }}"
      hardware:
        num_cpus: 4
        nested_virt: yes
        memory_mb: 16384
      disk:
      - size_gb: 200
        controller_type: "nvme"
        controller_number: 0
        unit_number: 0
        type: thin
        datastore: "{{ item[0].ds }}"
      networks:
      - name: "{{ item[0].id}}-Trunk"
        device_type: vmxnet3
      - name: "{{ item[0].id}}-Trunk"
        device_type: vmxnet3
      - name: "{{ item[0].id}}-Trunk"
        device_type: vmxnet3
      - name: "{{ item[0].id}}-Trunk"
        device_type: vmxnet3
      cdrom:
      - controller_number: 0
        unit_number: 0
        state: present
        type: iso
        iso_path: "[{{ item[0].ds }}]\\ISO\\VMware-VMvisor-Installer-9.0.1-LegacyCPU.iso"
    loop: "{{ LAB_SID | product(LAB_ESX_VMs) | list }}"
    delegate_to: localhost
    register: create_lab_esxi_vms

  - name: 03. Create TrueNAS Storage VM
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: '{{datacenter_name}}'
      folder: "{{ parent_folder }}{{ item[0].id }}"
      name: "{{ item[0].id }}-Truenas"
      state: poweredoff
      guest_id: freebsd13_64Guest
      esxi_hostname: "{{ item[0].host }}"
      hardware:
        num_cpus: 2
        nested_virt: yes
        memory_mb: 8192
      disk:
      - size_gb: 40
        controller_type: 'paravirtual'
        controller_number: 0
        unit_number: 0
        type: thin
        datastore: "{{ item[0].ds }}"
      - size_gb: 100
        controller_type: 'nvme'
        controller_number: 0
        unit_number: 0
        datastore: "{{ item[0].ds }}"
      - size_gb: 100
        controller_type: 'nvme'
        controller_number: 0
        unit_number: 1
        datastore: "{{ item[0].ds }}"
      - size_gb: 100
        controller_type: 'nvme'
        controller_number: 0
        unit_number: 2
        datastore: "{{ item[0].ds }}"
      - size_gb: 100
        controller_type: 'nvme'
        controller_number: 0
        unit_number: 3
        datastore: "{{ item[0].ds }}"          
      networks:
      - name: "{{ item[0].id }}-iSCSI-1"
        device_type: vmxnet3
        label: "Network Adapter 1"
      - name: "{{ item[0].id }}-iSCSI-2"
        device_type: vmxnet3
        label: "Network Adapter 2"
      cdrom:
      - controller_number: 0
        unit_number: 0
        state: present
        type: iso
        iso_path: "[{{ item[0].ds }}]\\ISO\\TrueNAS-SCALE-25.10.1.iso"
    loop: "{{ LAB_SID }}"        
    delegate_to: localhost
