---
- name: Deploy Ansible Lab
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "vcsa.vclass.rapa"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "VMware123!"
    datacenter_name: "RAPA" 
    esxi_username: "root"
    esxi_password: "VMware123!"
    parent_folder: "3.Class/" 
    snapshot_name: "Setup"

    LAB_SID: 
    - { id: S00, host: esx-01.vclass.rapa, ds: vSAN-ESX-01, Temp_DC: Temp-WinSvr-ESX-01, Temp_Desktop: Temp-Desktop-ESX-01, Temp_Server: Temp-Server-ESX-01 }
    - { id: S01, host: esx-01.vclass.rapa, ds: vSAN-ESX-01, Temp_DC: Temp-WinSvr-ESX-01, Temp_Desktop: Temp-Desktop-ESX-01, Temp_Server: Temp-Server-ESX-01 }
    - { id: S02, host: esx-01.vclass.rapa, ds: vSAN-ESX-01, Temp_DC: Temp-WinSvr-ESX-01, Temp_Desktop: Temp-Desktop-ESX-01, Temp_Server: Temp-Server-ESX-01 }
    - { id: S03, host: esx-01.vclass.rapa, ds: vSAN-ESX-01, Temp_DC: Temp-WinSvr-ESX-01, Temp_Desktop: Temp-Desktop-ESX-01, Temp_Server: Temp-Server-ESX-01 }
    - { id: S04, host: esx-01.vclass.rapa, ds: vSAN-ESX-01, Temp_DC: Temp-WinSvr-ESX-01, Temp_Desktop: Temp-Desktop-ESX-01, Temp_Server: Temp-Server-ESX-01 }
    - { id: S05, host: esx-02.vclass.rapa, ds: vSAN-ESX-02, Temp_DC: Temp-WinSvr-ESX-02, Temp_Desktop: Temp-Desktop-ESX-02, Temp_Server: Temp-Server-ESX-02 }
    - { id: S06, host: esx-02.vclass.rapa, ds: vSAN-ESX-02, Temp_DC: Temp-WinSvr-ESX-02, Temp_Desktop: Temp-Desktop-ESX-02, Temp_Server: Temp-Server-ESX-02 }
    - { id: S07, host: esx-02.vclass.rapa, ds: vSAN-ESX-02, Temp_DC: Temp-WinSvr-ESX-02, Temp_Desktop: Temp-Desktop-ESX-02, Temp_Server: Temp-Server-ESX-02 }
    - { id: S08, host: esx-02.vclass.rapa, ds: vSAN-ESX-02, Temp_DC: Temp-WinSvr-ESX-02, Temp_Desktop: Temp-Desktop-ESX-02, Temp_Server: Temp-Server-ESX-02 }
    - { id: S09, host: esx-02.vclass.rapa, ds: vSAN-ESX-02, Temp_DC: Temp-WinSvr-ESX-02, Temp_Desktop: Temp-Desktop-ESX-02, Temp_Server: Temp-Server-ESX-02 }

    LAB_PGs:
    - { name: -Trunk,   vid: 4095 }
    - { name: -Mgmt,    vid:   10 }

    LAB_VMs:
    - { name: prod-k8s-api-proxy01 }
    - { name: prod-k8s-api-proxy02 }
    - { name: prod-k8s-cp-01 }
    - { name: prod-k8s-cp-02 }
    - { name: prod-k8s-cp-03 }
    - { name: prod-k8s-worker-01 }
    - { name: prod-k8s-worker-02 }
    - { name: prod-k8s-worker-03 }

  tasks:
  - name: 01. Create LAB VM Folder
    community.vmware.vcenter_folder:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      folder_type: vm
      folder_name: "{{ item.id }}"
      parent_folder: "{{ parent_folder }}"
      state: present
    loop: "{{ LAB_SID }}"
    delegate_to: localhost


  - name: 02. Assign Permission to VM folder
    community.vmware.vmware_object_role_permission:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: false
      role: Administrator
      principal: "vclass.rapa\\{{ item.id }}"
      object_name: '{{ item.id }}'
      state: present
    loop: "{{ LAB_SID }}"
    delegate_to: localhost


  - name: 03. Create LAB Standard vSwitch
    community.vmware.vmware_vswitch:
      hostname: "{{ item.host }}"
      username: "{{ esxi_username }}"
      password: "{{ esxi_password }}"
      validate_certs: no
      switch: "{{ item.id }}"
      mtu: 9000
      security:
        promiscuous_mode: True
        mac_changes: True
        forged_transmits: True      
    loop: "{{ LAB_SID }}"
    delegate_to: localhost


  - name: Waiting previous task complated
    wait_for:
      timeout: 10
    delegate_to: localhost


  - name: 04. Adding LAB Portgroups to LAB Switch
    community.vmware.vmware_portgroup:
      hostname: "{{ item[0].host }}"
      username: "{{ esxi_username }}"
      password: "{{ esxi_password }}"
      esxi_hostname: "{{ item[0].host }}"
      validate_certs: no
      switch: "{{ item[0].id }}"
      portgroup: "{{ item[0].id }}{{ item[1].name }}"
      vlan_id: "{{ item[1].vid }}"
    loop: "{{ LAB_SID | product(LAB_PGs) | list }}"
    delegate_to: localhost


  - name: 05. Deploy Lab DC vm
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item.id }}-DC"
      datacenter: "{{ datacenter_name }}"
      folder: "{{ parent_folder }}{{ item.id }}"
      esxi_hostname: "{{ item.host }}"
      datastore: "{{ item.ds }}"
      template: "{{ item.Temp_DC }}"
      linked_clone: True
      snapshot_src: "{{ snapshot_name }}"
    loop: "{{ LAB_SID }}"
    delegate_to: localhost


  - name: 06. Change Lab DC vm networks
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item.id }}-DC"
      datacenter: "{{ datacenter_name }}"
      folder: "{{ parent_folder }}{{ item.id }}"
      esxi_hostname: "{{ item.host }}"
      datastore: "{{ item.ds }}"
      networks:
        - name: "{{ item.id }}-Trunk"
          label: "Network adapter 1"
        - name: "VM-192.168.1.x"
          label: "Network adapter 2"
    loop: "{{ LAB_SID }}"
    delegate_to: localhost


  - name: 08. Poweron Lab DC vm
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item.id }}-DC"
      state: "poweredon"
    loop: "{{ LAB_SID }}"
    delegate_to: localhost


  - name: 09. Deploy Lab Desktop vm
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item.id }}-Desktop"
      datacenter: "{{ datacenter_name }}"
      folder: "{{ parent_folder }}{{ item.id }}"
      esxi_hostname: "{{ item.host }}"
      datastore: "{{ item.ds }}"
      template: "{{ item.Temp_Desktop}}"
      linked_clone: True
      snapshot_src: "{{ snapshot_name }}"
    loop: "{{ LAB_SID }}"
    delegate_to: localhost


  - name: 10. Change Lab Desktop vm networks
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item.id }}-Desktop"
      datacenter: "{{ datacenter_name }}"
      folder: "{{ parent_folder }}{{ item.id }}"
      esxi_hostname: "{{ item.host }}"
      datastore: "{{ item.ds }}"
      networks:
        - name: "{{ item.id }}-Mgmt"
          label: "Network adapter 1"
    loop: "{{ LAB_SID }}"
    delegate_to: localhost


  - name: 11. Poweron Lab Desktop vm
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item.id }}-Desktop"
      state: "poweredon"
    loop: "{{ LAB_SID }}"
    delegate_to: localhost


  - name: 12. Deploy Ansible Lab vm
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ item[0].id }}-{{ item[1].name }}"
      datacenter: "{{ datacenter_name }}"
      folder: "{{ parent_folder }}{{ item[0].id }}"
      esxi_hostname: "{{ item[0].host }}"
      datastore: "{{ item[0].ds }}"
      template: "{{ item[0].Temp_Server }}"
      linked_clone: True
      snapshot_src: "{{ snapshot_name }}"
    loop: "{{ LAB_SID | product(LAB_VMs) | list }}"
    delegate_to: localhost
